language: go

go:
  - "1.10"
  - "1.11"
  - "1.12"
  - "master"

before_install:
  - go get -u golang.org/x/lint/golint

install: true

script:
  - go build .
  - golint -set_exit_status ./...
  - >
    GOFMT_DIFF=$(gofmt -d .);
    if [ -n "$GOFMT_DIFF" ]; then
      printf %s "$GOFMT_DIFF";
      exit 1;
    else
      exit 0;
    fi
  - go vet ./...
  - go test -v ./...
